name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: 'build'
      uses: skbeh/mpv-winbuild-action@main

